import { makeStyles } from "tss-react/mui";

// ── Design tokens ─────────────────────────────────────────────────────────────
const tok = {
  base: "#0A0B0F",
  surface: "#111318",
  elevated: "#181B22",
  border: "#232630",
  accentBlue: "#6C77E8",
  accentBlueDim: "#3D4580",
  accentGlow: "rgba(108,119,232,0.15)",
  danger: "#C0514E",
  text: {
    primary: "#F0F2FF",
    secondary: "#8B93B0",
    muted: "#4D5470",
    accent: "#6C77E8",
  },
};

const caseStudyDetail1Styles = makeStyles()(() => ({
  // ── ROOT ──────────────────────────────────────────────────────────────────
  pageWrapper: {
    width: "100%",
    minHeight: "100vh",
    background: tok.base,
    overflowX: "hidden",
  },

  // ── NAVBAR ────────────────────────────────────────────────────────────────
  navbar: {
    width: "100%",
    height: 64,
    background: `${tok.base}F0`,
    backdropFilter: "blur(16px)",
    borderBottom: `1px solid ${tok.border}`,
    display: "flex",
    alignItems: "center",
    padding: "0 40px",
    position: "sticky",
    top: 0,
    zIndex: 100,
  },
  navbarName: {
    fontFamily: "Geist, sans-serif",
    fontWeight: 700,
    fontSize: 18,
    color: tok.text.primary,
    letterSpacing: "-0.4px",
  },

  // ── HERO ──────────────────────────────────────────────────────────────────
  heroSection: {
    width: "100%",
    background: tok.base,
    padding: "72px 40px 56px",
  },
  heroLabel: {
    fontFamily: "Inter, sans-serif",
    fontWeight: 600,
    fontSize: 11,
    color: tok.text.accent,
    letterSpacing: "0.14em",
    textTransform: "uppercase",
    marginBottom: 28,
    display: "flex",
    alignItems: "center",
    gap: 10,
  },
  heroLabelLine: {
    display: "inline-block",
    width: 28,
    height: 2,
    background: tok.accentBlue,
    borderRadius: 2,
    flexShrink: 0,
  },
  heroTitle: {
    fontFamily: "Geist, sans-serif",
    fontWeight: 800,
    fontSize: "clamp(48px, 6vw, 80px)",
    lineHeight: 1.06,
    color: tok.text.primary,
    letterSpacing: "-2.5px",
    marginBottom: 28,
    maxWidth: 880,
    whiteSpace: "pre-line",
  },
  heroSubtitle: {
    fontFamily: "Inter, sans-serif",
    fontWeight: 400,
    fontSize: 18,
    color: tok.text.secondary,
    lineHeight: 1.75,
    marginBottom: 56,
    maxWidth: 600,
  },
  heroMeta: {
    display: "flex",
    flexWrap: "wrap",
    borderTop: `1px solid ${tok.border}`,
    paddingTop: 32,
    gap: "16px 0",
  },
  heroMetaItem: {
    paddingRight: 56,
    paddingTop: 4,
    borderRight: `1px solid ${tok.border}`,
    marginRight: 56,
    "&:last-child": { borderRight: "none", paddingRight: 0, marginRight: 0 },
  },
  heroMetaLabel: {
    fontFamily: "Inter, sans-serif",
    fontWeight: 500,
    fontSize: 10,
    color: tok.text.muted,
    textTransform: "uppercase",
    letterSpacing: "0.12em",
    marginBottom: 8,
  },
  heroMetaValue: {
    fontFamily: "Geist, sans-serif",
    fontWeight: 600,
    fontSize: 15,
    color: tok.text.primary,
    whiteSpace: "pre-line",
  },
  heroImageWrapper: {
    width: "100%",
    height: 560,
    background: tok.surface,
    borderRadius: 20,
    border: `1px solid ${tok.border}`,
    marginTop: 56,
    overflow: "hidden",
    position: "relative",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  heroImageGlow: {
    position: "absolute",
    inset: 0,
    background: `radial-gradient(ellipse at 55% 40%, ${tok.accentGlow} 0%, transparent 65%)`,
    pointerEvents: "none",
  },
  heroImageLabel: {
    fontFamily: "Inter, sans-serif",
    fontSize: 12,
    color: tok.text.muted,
    letterSpacing: "0.06em",
    zIndex: 1,
  },

  // ── TWO-COLUMN SECTION BASE ────────────────────────────────────────────────
  twoColSection: {
    width: "100%",
    borderTop: `1px solid ${tok.border}`,
    display: "flex",
    gap: 80,
    alignItems: "flex-start",
    padding: "96px 40px",
  },
  sectionLeftCol: {
    width: 260,
    flexShrink: 0,
  },
  sectionEyebrow: {
    fontFamily: "Inter, sans-serif",
    fontWeight: 600,
    fontSize: 10,
    color: tok.text.muted,
    textTransform: "uppercase",
    letterSpacing: "0.14em",
    marginBottom: 10,
  },
  sectionHeading: {
    fontFamily: "Geist, sans-serif",
    fontWeight: 800,
    fontSize: 34,
    color: tok.text.primary,
    letterSpacing: "-1px",
    lineHeight: 1.1,
  },
  sectionHeadingAccent: {
    color: tok.text.accent,
  },

  // ── OVERVIEW ──────────────────────────────────────────────────────────────
  overviewSection: {
    width: "100%",
    padding: "96px 40px",
    background: tok.surface,
    borderTop: `1px solid ${tok.border}`,
    display: "flex",
    gap: 80,
    alignItems: "flex-start",
  },
  overviewText: {
    fontFamily: "Inter, sans-serif",
    fontWeight: 400,
    fontSize: 18,
    color: tok.text.secondary,
    lineHeight: 1.85,
    flex: 1,
  },

  // ── THE PROBLEM ───────────────────────────────────────────────────────────
  problemSection: {
    width: "100%",
    background: tok.base,
    padding: "96px 40px",
    borderTop: `1px solid ${tok.border}`,
  },
  problemSectionHeader: {
    marginBottom: 48,
  },
  problemCardsRow: {
    display: "flex",
    gap: 16,
    flexWrap: "wrap",
  },
  problemCard: {
    flex: "1 1 280px",
    background: tok.surface,
    borderRadius: 18,
    border: `1px solid ${tok.border}`,
    padding: "36px 32px",
    transition: "border-color 0.25s, transform 0.25s",
    cursor: "default",
    "&:hover": {
      borderColor: tok.accentBlueDim,
      transform: "translateY(-2px)",
    },
  },
  problemIconBar: {
    width: 28,
    height: 4,
    background: tok.danger,
    borderRadius: 3,
    marginBottom: 28,
  },
  problemCardTitle: {
    fontFamily: "Geist, sans-serif",
    fontWeight: 700,
    fontSize: 17,
    color: tok.text.primary,
    letterSpacing: "-0.3px",
    marginBottom: 12,
  },
  problemCardText: {
    fontFamily: "Inter, sans-serif",
    fontWeight: 400,
    fontSize: 14,
    color: tok.text.secondary,
    lineHeight: 1.75,
  },

  // ── MY ROLE ───────────────────────────────────────────────────────────────
  roleSection: {
    width: "100%",
    padding: "96px 40px",
    background: tok.surface,
    borderTop: `1px solid ${tok.border}`,
    display: "flex",
    gap: 80,
    alignItems: "flex-start",
  },
  roleItems: {
    flex: 1,
    display: "flex",
    flexDirection: "column",
  },
  roleItem: {
    display: "flex",
    alignItems: "flex-start",
    gap: 20,
    padding: "28px 0",
    borderBottom: `1px solid ${tok.border}`,
    "&:first-of-type": { paddingTop: 0 },
    "&:last-child": { borderBottom: "none" },
  },
  roleIconDot: {
    width: 7,
    height: 7,
    background: tok.accentBlue,
    borderRadius: "50%",
    marginTop: 9,
    flexShrink: 0,
    boxShadow: `0 0 10px ${tok.accentBlue}`,
  },
  roleItemTitle: {
    fontFamily: "Geist, sans-serif",
    fontWeight: 700,
    fontSize: 16,
    color: tok.text.primary,
    letterSpacing: "-0.2px",
    marginBottom: 6,
  },
  roleItemText: {
    fontFamily: "Inter, sans-serif",
    fontWeight: 400,
    fontSize: 14,
    color: tok.text.secondary,
    lineHeight: 1.75,
  },

  // ── THE JOURNEY ───────────────────────────────────────────────────────────
  journeySection: {
    width: "100%",
    background: tok.base,
    borderTop: `1px solid ${tok.border}`,
    padding: "96px 40px",
  },
  journeyHeadingRow: {
    marginBottom: 64,
  },
  journeyItem: {
    display: "flex",
    alignItems: "flex-start",
    gap: 28,
    marginBottom: 72,
    position: "relative",
  },
  journeyDotCol: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    paddingTop: 4,
  },
  journeyDot: {
    width: 14,
    height: 14,
    background: tok.accentBlue,
    border: `3px solid ${tok.base}`,
    borderRadius: "50%",
    flexShrink: 0,
    boxShadow: `0 0 14px ${tok.accentBlue}`,
    zIndex: 1,
  },
  journeyConnector: {
    width: 1,
    flex: 1,
    minHeight: 40,
    background: `linear-gradient(to bottom, ${tok.accentBlueDim}, transparent)`,
    marginTop: 6,
  },
  journeyContent: {
    flex: 1,
  },
  journeyPhaseRow: {
    display: "flex",
    alignItems: "center",
    gap: 14,
    marginBottom: 20,
    flexWrap: "wrap",
  },
  journeyPhaseTag: {
    fontFamily: "Inter, sans-serif",
    fontWeight: 600,
    fontSize: 10,
    color: tok.text.accent,
    textTransform: "uppercase",
    letterSpacing: "0.1em",
    background: tok.accentGlow,
    padding: "4px 12px",
    borderRadius: 6,
    border: `1px solid ${tok.accentBlueDim}`,
  },
  journeyPhaseTitle: {
    fontFamily: "Geist, sans-serif",
    fontWeight: 700,
    fontSize: 22,
    color: tok.text.primary,
    letterSpacing: "-0.5px",
  },
  journeyText: {
    fontFamily: "Inter, sans-serif",
    fontWeight: 400,
    fontSize: 15,
    color: tok.text.secondary,
    lineHeight: 1.85,
    marginBottom: 14,
  },
  journeyInsightBox: {
    background: tok.surface,
    borderRadius: 12,
    border: `1px solid ${tok.accentBlueDim}`,
    borderLeft: `3px solid ${tok.accentBlue}`,
    padding: "22px 28px",
    marginTop: 24,
  },
  journeyInsightLabel: {
    fontFamily: "Inter, sans-serif",
    fontWeight: 600,
    fontSize: 10,
    color: tok.text.accent,
    textTransform: "uppercase",
    letterSpacing: "0.12em",
    marginBottom: 10,
  },
  journeyInsightText: {
    fontFamily: "Geist, sans-serif",
    fontWeight: 500,
    fontSize: 17,
    color: tok.text.primary,
    fontStyle: "italic",
    lineHeight: 1.6,
  },

  // ── DESIGN SOLUTIONS ──────────────────────────────────────────────────────
  solutionsSection: {
    width: "100%",
    background: tok.surface,
    borderTop: `1px solid ${tok.border}`,
    padding: "96px 40px",
  },
  solutionCard: {
    background: tok.elevated,
    borderRadius: 20,
    border: `1px solid ${tok.border}`,
    padding: "40px",
    marginBottom: 16,
    transition: "border-color 0.25s",
    "&:hover": { borderColor: tok.accentBlueDim },
  },
  solutionCardTitle: {
    fontFamily: "Geist, sans-serif",
    fontWeight: 700,
    fontSize: 20,
    color: tok.text.primary,
    letterSpacing: "-0.4px",
    marginBottom: 10,
  },
  solutionCardText: {
    fontFamily: "Inter, sans-serif",
    fontWeight: 400,
    fontSize: 14,
    color: tok.text.secondary,
    lineHeight: 1.75,
    maxWidth: 640,
  },
  phoneMockupRow: {
    display: "flex",
    gap: 28,
    marginTop: 32,
    justifyContent: "center",
    flexWrap: "wrap",
  },
  phoneMockup: {
    width: 280,
    height: 600,
    background: tok.surface,
    borderRadius: 20,
    border: `1px solid ${tok.border}`,
    boxShadow: `0 8px 32px rgba(0,0,0,0.4)`,
  },
  m3SwatchRow: {
    display: "flex",
    gap: 10,
    marginTop: 28,
  },
  m3Swatch: {
    height: 52,
    flex: 1,
    borderRadius: 10,
    border: `1px solid ${tok.border}`,
  },
  offlineLabel: {
    fontFamily: "Inter, sans-serif",
    fontWeight: 600,
    fontSize: 10,
    color: tok.text.accent,
    textTransform: "uppercase",
    letterSpacing: "0.12em",
    marginBottom: 10,
  },
  offlineText: {
    fontFamily: "Inter, sans-serif",
    fontWeight: 400,
    fontSize: 14,
    color: tok.text.secondary,
    lineHeight: 1.75,
  },
  offlineSolutionBox: {
    background: tok.base,
    borderRadius: 14,
    border: `1px solid ${tok.border}`,
    padding: "28px",
    flex: 1,
    minWidth: 260,
  },
  offlineBulletRow: {
    display: "flex",
    alignItems: "flex-start",
    gap: 12,
    marginBottom: 14,
  },
  offlineBulletDot: {
    width: 6,
    height: 6,
    minWidth: 6,
    background: tok.accentBlue,
    borderRadius: "50%",
    marginTop: 7,
    boxShadow: `0 0 6px ${tok.accentBlue}`,
  },
  offlineBulletText: {
    fontFamily: "Inter, sans-serif",
    fontWeight: 400,
    fontSize: 14,
    color: tok.text.secondary,
    lineHeight: 1.65,
  },
  offlineSmallDot: {
    width: 5,
    height: 5,
    background: tok.text.muted,
    borderRadius: "50%",
    flexShrink: 0,
    marginTop: 7,
  },
  offlineSmallText: {
    fontFamily: "Inter, sans-serif",
    fontWeight: 400,
    fontSize: 13,
    color: tok.text.secondary,
  },
  offlineImpactLabel: {
    fontFamily: "Geist, sans-serif",
    fontWeight: 600,
    fontSize: 13,
    color: tok.text.primary,
    marginBottom: 6,
  },
  offlineImpactText: {
    fontFamily: "Inter, sans-serif",
    fontWeight: 400,
    fontSize: 13,
    color: tok.text.secondary,
    lineHeight: 1.65,
  },

  // ── USER TESTING ──────────────────────────────────────────────────────────
  userTestingSection: {
    width: "100%",
    padding: "96px 40px",
    background: tok.base,
    borderTop: `1px solid ${tok.border}`,
    display: "flex",
    gap: 80,
    alignItems: "flex-start",
  },
  userTestingText: {
    fontFamily: "Inter, sans-serif",
    fontWeight: 400,
    fontSize: 17,
    color: tok.text.secondary,
    lineHeight: 1.85,
    flex: 1,
  },

  // ── IMPACT ────────────────────────────────────────────────────────────────
  impactSection: {
    width: "100%",
    background: tok.accentBlue,
    backgroundImage: `radial-gradient(ellipse at 25% 60%, #8B94F0 0%, ${tok.accentBlue} 45%, #4A54C8 100%)`,
    padding: "96px 40px",
  },
  impactEyebrow: {
    fontFamily: "Inter, sans-serif",
    fontWeight: 600,
    fontSize: 10,
    color: "rgba(255,255,255,0.55)",
    textTransform: "uppercase",
    letterSpacing: "0.16em",
    textAlign: "center",
    marginBottom: 60,
  },
  impactCardsRow: {
    display: "flex",
    justifyContent: "center",
    flexWrap: "wrap",
  },
  impactCard: {
    flex: "0 1 280px",
    textAlign: "center",
    padding: "0 48px",
    borderRight: "1px solid rgba(255,255,255,0.18)",
    "&:last-child": { borderRight: "none" },
  },
  impactNumber: {
    fontFamily: "Geist, sans-serif",
    fontWeight: 800,
    fontSize: 88,
    color: "#FFFFFF",
    lineHeight: 1,
    marginBottom: 12,
    letterSpacing: "-4px",
  },
  impactDesc: {
    fontFamily: "Inter, sans-serif",
    fontWeight: 500,
    fontSize: 14,
    color: "rgba(255,255,255,0.72)",
    letterSpacing: "0.03em",
    textTransform: "uppercase",
  },

  // ── LEARNINGS ─────────────────────────────────────────────────────────────
  learningsSection: {
    width: "100%",
    padding: "96px 40px",
    background: tok.surface,
    borderTop: `1px solid ${tok.border}`,
    display: "flex",
    gap: 80,
    alignItems: "flex-start",
  },
  learningsRight: {
    flex: 1,
  },
  learningItem: {
    display: "flex",
    gap: 20,
    padding: "28px 0",
    borderBottom: `1px solid ${tok.border}`,
    "&:first-of-type": { paddingTop: 0 },
    "&:last-child": { borderBottom: "none" },
  },
  learningNumber: {
    fontFamily: "Geist, sans-serif",
    fontWeight: 700,
    fontSize: 12,
    color: tok.text.accent,
    flexShrink: 0,
    paddingTop: 3,
    letterSpacing: "0.05em",
  },
  learningText: {
    fontFamily: "Inter, sans-serif",
    fontWeight: 400,
    fontSize: 15,
    color: tok.text.secondary,
    lineHeight: 1.8,
  },
  reflectionBox: {
    marginTop: 40,
    padding: "28px 32px",
    background: tok.elevated,
    border: `1px solid ${tok.border}`,
    borderLeft: `3px solid ${tok.accentBlue}`,
    borderRadius: 12,
  },
  reflectionText: {
    fontFamily: "Geist, sans-serif",
    fontWeight: 500,
    fontSize: 17,
    color: tok.text.primary,
    lineHeight: 1.75,
    letterSpacing: "-0.3px",
  },

  // ── FOOTER ────────────────────────────────────────────────────────────────
  footer: {
    width: "100%",
    background: tok.base,
    borderTop: `1px solid ${tok.border}`,
    padding: "48px 40px",
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    flexWrap: "wrap",
    gap: 20,
  },
  footerName: {
    fontFamily: "Geist, sans-serif",
    fontWeight: 700,
    fontSize: 15,
    color: tok.text.primary,
    marginBottom: 4,
  },
  footerCopy: {
    fontFamily: "Inter, sans-serif",
    fontWeight: 400,
    fontSize: 12,
    color: tok.text.muted,
  },
  footerEmail: {
    fontFamily: "Inter, sans-serif",
    fontWeight: 600,
    fontSize: 13,
    color: tok.text.accent,
  },
}));

export default caseStudyDetail1Styles;
